### ISSUE TITLE
Contact list

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#10]
# Value Proposition

**As a** user 
**I need** to select the right contact    
**to be able to** get easily in touch with one of my contacts

# Description

<img width="290" alt="Screenshot 2022-05-09 at 14 53 10" src="https://user-images.githubusercontent.com/101577847/167421092-2c8fc0af-5e11-41fe-9fd9-1ef92cb06cbb.png">

# Acceptance Criteria

- [ ] The user sees all contacts together in one page
- [ ] All users are shown in alphabetical order 
- [ ] The user is able to scroll up and down the contact list      
- [ ] Every contact is displayed in a single card
- [ ] Every contact card shows the most important contact details (name, job, company)
- [ ] Every contact card has a dial button which connects to the dial function of the users phone 
- [ ] Every contact card has an e-mail button which connects to the e-mail function of the users phone
- [ ] A search bar is displayed to select one specific contact 
- [ ] A filter button is displayed to sort out contacts due to specific criteria
- [ ] After hitting the filter button a tag list appears
- [ ] Within this tag list several tag buttons are shown and can be tapped/clicked
- [ ] Tapping/clicking the tags filters the contact cards with the same tag
- [ ] The user can bookmark any contact card
- [ ] A bookmarked contact card is marked for the user 
- [ ] Tags can be added via the input field by the user
- [ ] In the footer the icons of the four main features of the app are displayed 
- [ ] The footer icons displaying icons of the 1) personal profile 2) the qr code 3) the add contact page 4) contact list
- [ ] The appearance of the icons in the footer bar are changing and displaying which page the user is currently using               

# Tasks

(for developers team)

- [ ] Test is written checking the display of all necessary data from the database 
- [ ] Test is written for checking the connection to the database
- [ ] Create an ordered list displaying all contacts    
- [ ] Sort the ordered list from a to z on default
- [ ] Create a single card component with the contact details 1) name 2) job/position 3) company
- [ ] Add a dial button to the card
- [ ] Add an e-mail button to the card 
- [ ] Connect the dial button with the dial function in the phone
- [ ] Connect the e-mail button with the e-mail function in the phone
- [ ] Create a list showing all single card components in row 
- [ ] Make the contact list scrollable on screen
- [ ] Add a bookmark component 
- [ ] Add a search bar to the top of the page
- [ ] Add a search icon next to the search bar
- [ ] Add a filter icon next to the search icon  
- [ ] Add a search filter function to the search bar
- [ ] Sort the the single cards after every single character the user types in the search bar 
- [ ] Add a toggle function to the search bar in order to toggle from search filter to tag filter and back depending on which button is currently active 
- [ ] Add a tag filter function to the filter bar    
- [ ] Add a footer to the page
- [ ] Add footer icons displaying icons the main features 1) personal profile 2) the qr code 3) the add contact page 4) contact list
- [ ] Add a toggle function in order to change the appearance of a footer icon depending on which which page the user is currently using
- [ ] Add all tags to an unordered list 
- [ ] Add a tag list function displaying a tag bar showing the top 10 tags (depending on usage)
- [ ] Add a single list item for every tag 
- [ ] Add an add button in order to add tags to the tag list
- [ ] Add a toggle color for the tags displaying   
- [ ] Add a toggle color for the dial button
- [ ] Add a toggle color for the e-mail button
- [ ] Add a bookmark function to the tags in the tag list  
- [ ] ...

# Complexity
XL
