### ISSUE TITLE
Edit Button QR Code

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#11]
# Value Proposition

**As a** user
**I need** to edit contact details manually
**to be able to** add a contact

# Description

Edit button labeled with "edit" 

# Acceptance Criteria

-[ ] The user can identify the edit button on first sight  
-[ ] The user can tap/click the edit button
-[ ] The user gets forwarded to the contact details form after hitting the button

# Tasks

(for developers team)

- [ ] Test is written for the button
- [ ] Use Storybook for creating a style draft 
- [ ] Add an edit button with a link to the contact form page  
- [ ] Edit button changes color when tapped/clicked
- [ ] Edit button forwards to an edit form page when tapped/clicked

# Complexity
S
