### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#12]
# Value Proposition

**As a** user
**I need** to leave the current page  
**to be able to** to get to another feature

# Description

Back button allows the user to visit the previous page 

# Acceptance Criteria

- [ ] The user can identify the back button on first sight  
- [ ] The user can tap/click the edit button
- [ ] The user gets back to the previous page after hitting the button

# Tasks

(for developers team)

- [ ] Test is written for the button
- [ ] Use Storybook for creating a style draft 
- [ ] Create a back button component
- [ ] Connect the back button with a link to the previous page  
- [ ] Add to styles to the back button. It changes its color when tapped/clicked

# Complexity
S
