### ISSUE TITLE
Single Contact Card

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#16]
# Value Proposition

**As a** user 
**I need** to see a single contact card      
**to be able to** get easily in touch with one of my contacts

# Description

<img width="290" alt="Screenshot 2022-05-09 at 14 53 10" src="https://user-images.githubusercontent.com/101577847/167421092-2c8fc0af-5e11-41fe-9fd9-1ef92cb06cbb.png">

# Acceptance Criteria

- [ ] The user sees all contacts together in one page
- [ ] All contacts are shown in alphabetical order 
- [ ] The user is able to scroll up and down the contact list      
- [ ] The user finds every contact in a single contact card
- [ ] The user sees the most important contact details (1) name, 2) job, 3) company) in a contact card
- [ ] The user can hit the dial button in every card to directly call the selected contact
- [ ] The user can hit the e-mail button in every card and gets directly forwarded to its email client
- [ ] The user can filter via search bar  
- [ ] The user sees a filter button to sort out contacts by hitting the button. After hitting the filter button a tag bar appears 
- [ ] The user can filter its contacts by bookmarking tags   
- [ ] The user can bookmark any contact card
- [ ] A bookmarked contact card is marked for the user   
- [ ] The user can access the the main features  1) personal profile 2) the qr code 3) the add contact page 4) contact list via icons at the footer bar   
- [ ] The user sees what page its on by a marked icon at the footer bar                

# Tasks

(for developers team)

- [ ] Test is written checking the display of all necessary data from the database 
- [ ] Test is written for checking the connection to the database
- [ ] Create an ordered list displaying all contacts    
- [ ] Sort the ordered list from a to z on default by default
- [ ] Create a single card component with the contact details 1) name 2) job/position 3) company
- [ ] Add a dial button to the card
- [ ] Add an e-mail button to the card 
- [ ] Connect the dial button with the dial function in the phone
- [ ] Connect the e-mail button with the e-mail function in the phone
- [ ] Create a list showing all single card components in row 
- [ ] Make the contact list scrollable on screen
- [ ] Add a bookmark component 
- [ ] Add a search bar to the top of the page
- [ ] Add a search icon next to the search bar
- [ ] Add a filter icon next to the search icon  
- [ ] Add a search filter function to the search bar
- [ ] Sort the the single cards after every single character the user types in the search bar 
- [ ] Add a toggle function to the search bar in order to toggle from search filter to tag filter and back depending on which button is currently active 
- [ ] Add a tag filter function to the filter bar    
- [ ] Add a footer to the page
- [ ] Add footer icons displaying icons the main features 1) personal profile 2) the qr code 3) the add contact page 4) contact list
- [ ] Add a toggle function in order to change the appearance of a footer icon depending on which which page the user is currently using
- [ ] Add all tags to an unordered list 
- [ ] Add a tag list function displaying a tag bar showing the top 10 tags (depending on usage)
- [ ] Add a single list item for every tag 
- [ ] Add an add button in order to add tags to the tag list
- [ ] Add a toggle color for the tags displaying   
- [ ] Add a toggle color for the dial button
- [ ] Add a toggle color for the e-mail button
- [ ] Add a bookmark function to the tags in the tag list  
- [ ] ...

# Complexity
XL
