### ISSUE TITLE
[TBE]Implementing Routes  

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#22]
# Value Proposition

**As a** user 
**I need** to switch pages or get forwarded to other pages
**to be able to** access the features of the pages

# Description

Scribble / design or text

# Acceptance Criteria

- [ ] After I hit submit on the my contact detail form I get forwarded to the my contact details page  
- [ ] 
- [ ] ...

# Tasks

(for developers team)

- [ ] list the tasks that need to be performed within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...

# Complexity
