### ISSUE TITLE
My Contact Card

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#23]
# Value Proposition

**As a** user 
**I need** to see a single contact card      
**to be able to** see all details of my contact 

# Description

 The single contact card displays the main information of a single contact

# Acceptance Criteria           

- [ ] First name is shown 
- [ ] Last name is shown
- [ ] Job/Position is shown
- [ ] Company is shown
- [ ] Phone number is shown
- [ ] E-mail is shown

# Tasks

(for developers team)

- [ ] Create a branch
- [ ] Create a component 
- [ ] Add headline including a variable for first name and last name
- [ ] Add a paragraph including a variable for job
- [ ] Add a paragraph including a variable for company
- [ ] Add a paragraph including a variable for phone 
- [ ] Add a paragraph including a variable for e-mail
- [ ] Add a paragraph including a link to the website
- [ ] Add a dial button 
- [ ] Add an e-mail button 

# Complexity
S
