### ISSUE TITLE
Footer Nav Bar 

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#24]
# Value Proposition

**As a** user 
**I need** to navigate 
**to be able to** access different features

# Description

The footer nav bar allows the user to navigate between the different pages

# Acceptance Criteria

- [ ] The user sees all contacts together in one page
- [ ] All users are shown in alphabetical order      
- [ ] Every contact is displayed in a single contact card
- [ ] A search bar is displayed to select one specific contact  
         

# Tasks

(for developers team)

- [ ] Create a new branch   
- [ ] Create a footer bar component
- [ ] Add matching footer icons displaying icons of the pages 1) my contact card  2) the add contact page 3) contact list
- [ ] Make it sticky 
- [ ]…

# Complexity
S

**Comment by HishamAlmannai** [comment]
Hi Raimar,

good so far. Some comments:
I would add a sketch in the Description if available.

Furthermore it would make more sense to mention the three pages in the Acceptance criteria instead in Tasks.
Which are the "on relevant pages"?
The Icons are the Buttons / Links? Any mistakes considered?

How are you going to accomplish the routing?
What about testing?

**Comment by raimartontsch** [comment]
Moin @HishamAlmannai , 

thanks for your review! 

No sketch necessary at this point ;)
Acceptance criteria are updated.
I will implement routing at a later point via pages and links with next.js ;) 
Testing will be implemented in a different session.
