### ISSUE TITLE
Contact List 

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#25]
# Value Proposition

**As a** user 
**I need** to see all my contacts    
**to be able to** select one

# Description

A list of all contacts

# Acceptance Criteria

- [ ] The user sees all contacts together in one page
- [ ] All users are shown in alphabetical order      
- [ ] Every contact is displayed in a single contact card
- [ ] A search bar is displayed to select one specific contact  
         

# Tasks

(for developers team)

- [ ] Create a new branch  
- [ ] Create an ordered list displaying all single contact cards as list items
- [ ] Make local storage the source of the data for a single contact card using useStore
- [ ] Sort the ordered list from a to z on default 
- [ ] Add a search bar to the top of the page 
- [ ] ...

# Complexity
M
