### ISSUE TITLE
My Contact Profile 

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#28]
# Value Proposition

**As a** user
**I need**  access my profile 
**to be able to** see my contact details 

# Description

A user can access a single page displaying its personal contact details

# Acceptance Criteria

- [x] Personal contact details are shown on a single page

# Tasks

(for developers team)

- [ ] Create a new branch
- [ ] Create a new file named my-contact.js at the pages folder
- [ ] Add the MyContactCard component to my-contact.js 

# Complexity
S
