### ISSUE TITLE
Contact Profile Page 

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#29]
# Value Proposition

**As a** user
**I need**  access the profile of contact 
**to be able to** see its contact details 

# Description

A user can access a single page displaying the contact details of a contact

# Acceptance Criteria

- [ ] Contact details of contact are shown on a single page

# Tasks

(for developers team)

- [ ] Create a new branch
- [ ] Create a new file named [id].js at the pages folder
- [ ] Add the SingleContactCard component to [id].js

# Complexity
S
