### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#30]
# Value Proposition

**As a** user
**I need** a delete button 
**to be able to** to remove a contact from my contact list 

# Description

A delete button removes a contact from the contact list  

# Acceptance Criteria

- [ ] A delete button is displayed
- [ ] On click/tap the button deletes a contact

# Tasks

(for developers team)

- [ ] Create a new branch 
- [ ] Create a button component named DeleteButton 
- [ ] Add the button component to the SingleCard component
- [ ] Add a DeleteContact function to the useStore that removes a contact from the contact list 
- [ ] Add the DeleteContact function to the button  
- [ ] ...

# Complexity
