### ISSUE TITLE
Editr Button

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#32]
# Value Proposition

**As a** user
**I need** an edit button 
**to be able to** to edit a contacts  

# Description

An edit button opens a contact detail form where already existing contacts can be edited.   

# Acceptance Criteria

- [ ] An edit button is displayed
- [ ] After clicking/tapping the edit button the user sees a contact detail form where contact information can be edited.  

# Tasks

(for developers team)

- [ ] Create a new branch 
- [ ] Create a button component named EditButton 
- [ ] Add the button component to the contact/profile page of a single contact
- [ ] Add an EditContact function to useStore that opens a for with the contact information and allows the user to edit a contact  
- [ ] Link the button to the edit 
- [ ] ...

# Complexity
M

**Comment by irenepapaspyratos** [comment]
Hey Raimar, if you have more buttons, you could think about ONE button with variants instead of building a component for each.
I found a few typos: 
proposition => able to edit a contacts
tasks => that opens a for
Besides that, everything looks nice. :)

**Comment by raimartontsch** [comment]
Hi @irenepapaspyratos!
Thanks for your input. I have updated the user story so far.
