### ISSUE TITLE
Drop Down Menu - delete feature 

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#36]
# Value Proposition

**As a** user
**I need** to delete contacts  
**to be able to** to organize my contact list  

# Description

Via a drop down menu at the single contact card the user can delete already existing contacts   

# Acceptance Criteria

- [ ] A button for a drop down menu is displayed at a single contact card
- [ ] After clicking/tapping the drop down menu opens and shows the option "delete"
- [ ] After hitting delete the contact is deleted     

# Tasks

(for developers team)

- [ ] Create a new branch  
- [ ] Add a button to a single card 
- [ ] Name the button with "Menu"
- [ ] Add a drop down menu to the menu button
- [ ] Add "delete" to the drop down list
- [ ] Create a delete function at useStore and which deletes the selected contact 
- [ ] Apply the delete function to the delete list element   
- [ ] …

# Complexity
M
