### ISSUE TITLE
Add Routing 

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#39]
# Value Proposition

**As a** user 
**I need** to navigate 
**to be able to** access different features of the web app

# Description

The user is able to navigate on different pages in order to access different features

# Acceptance Criteria

- [ ] One main feature is displayed on every page
- [ ] A single contact is displayed on one page
- [ ] The user can navigate between the pages via a footer nav. bar

# Tasks

(for developers team)

- [ ] Create an new branch
- [ ] Create a file named [id].js in the pages folder
- [ ] Create a file named contact-list.js in the pages folder
- [ ] Create a file named add-contact.js in the pages folder
- [ ] Implement routing via next link
- [ ] Link the buttons at the footer nav. bar with its corresponding page
- [ ] Link the single contact card with its contact page
- [ ] ...

# Complexity

**Comment by raimartontsch** [comment]
Hi @F-Kirchhoff, 
many thanks for your review and your ideas! I updated this issue so far :)

**Comment by F-Kirchhoff** [comment]
Now its looking great! 🚀

**Comment by raimartontsch** [comment]
Thank you!!!
