### ISSUE TITLE
QR Code 

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#40]
# Value Proposition

**As a** user 
**I need** to display a qr code 
**to be able to** share contact details

# Description

The user can display a qr code for every contact to be able to share contact information 

# Acceptance Criteria

- [ ] A qr code button is displayed at every single contact card 
- [ ] By hitting the qr button the user gets displayed a unique qr code
- [ ] The qr code holds all the contact details of a user 

# Tasks

(for developers team)

- [ ] Create an new branch
- [ ] Add a library to the project that generates unique qr codes 
- [ ] Add a button to the single contact card component 
- [ ] Add a function that generates a qr code to every contact
- [ ] Add a modal state to the Store.js 
- [ ] Add the modal function to the qr code button
- [ ] Add an exit button to the qr modal window in order to close the modal window
     
# Complexity
M

**Comment by F-Kirchhoff** [comment]
Nice idea, can't wait to see the result. Not to complain here. 🦊
