### ISSUE TITLE
Start Screen

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#6]
# Value Proposition

**As a** user I open the app. 
**I need** to access the different main features of the app fast 
**to be able to** choose the feature I need right now. 

# Description

<img width="235" alt="Screenshot 2022-05-09 at 12 58 55" src="https://user-images.githubusercontent.com/101577847/167396723-1367461c-62f1-4d9a-92ea-cf35e8951d40.png">

# Acceptance Criteria

- [ ] The user sees the logo of the web and knows he/she picked the right app
- [ ] All main features the app provides are shown as icons
- [ ] All icons are show clearly the exact feature the user is looking for
- [ ] Tapping/Clicking a feature changes the color of the button 
- [ ] Tapping/Clicking and forwards the user to the feature page 

# Tasks

(for developers team)

- [ ] The logo of the app is displayed on the start screen
- [ ] All main features are displayed as icons at the screen
- [ ] Main features are 1) show contact list 2) add contact 3) got to my profile page  
- [ ] Every icon can be tapped/clicked 
- [ ] On tap/click the icon changes its color 
- [ ] On tap/click the icon forwards the user to the feature  

# Complexity
M

**Comment by PReichetanz** [comment]
Hello Raimar,

looks good so far!
I would adapt the value proposition to fit the example, i.e. something like

**As a** user
**I need to** have a landing page 
**in order to** access the different features of my app.

Besides, as long as you are not going to implement this landing page as your very first story, but only after you have implemented all the pages you link to, I think it is fine.

**Comment by raimartontsch** [comment]
Hi @PReichetanz! 

Thanks for your review. I adapted as proposed. 
The linking of the features to the feature pages will follow in a later user story.

**Comment by anitaschiller** [comment]
Hi Raimar, 
I think Paul is right - if there is e.g. no QR-Code functionality yet, then don't add the button to your start page now. Start with the buttons for the features that are already there and work. Later, when you build the QR-Code functionality, one of the tasks of the QR-Code user story would be to add the button to the start-page.

**Comment by doemser** [comment]
Are all features already implemented at the time of this user story? 

If not:
Do not implement a landing-page with buttons that do not work. Only implement buttons that work, always.
