### ISSUE TITLE
Show QR code

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#8]
# Value Proposition

**As a** user
**I need** to provide a link via qr code 
**to be able to** share my contact details fast and easy

# Description

<img width="220" alt="Screenshot 2022-05-09 at 14 17 19" src="https://user-images.githubusercontent.com/101577847/167408163-4683a9b3-2d4a-4952-9111-618af7c5228e.png">

# Acceptance Criteria

- [ ] The qr code holding all the contact details is displayed 
- [ ] In case the linking via qr code somehow does not work the user can access the add contact form via the edit button 
- [ ] The back button leads the user back to the starting page 

# Tasks

(for developers team)

- [ ] Test is written for the buttons
- [ ] Add an individual qr code to this page 
- [ ] Display this qr code prominently
- [ ] The qr code is linked to the contact details of the user  
- [ ] Add an edit button 
- [ ] Edit button changes color when tapped/clicked
- [ ] Edit button forwards to an edit form page when tapped/clicked
- [ ] Back button changes color when tapped/clicked
- [ ] Back button leads to starting page when tapped/clicked

# Complexity
M
