### ISSUE TITLE
Form contact details for profile

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project-nextjs#9]
# Value Proposition

**As a user**
**I need to fill in contact details** 
**to be able to provide all important information to business partners**

# Description

<img width="271" alt="Screenshot 2022-05-09 at 12 44 28" src="https://user-images.githubusercontent.com/101577847/167395184-ba0affa5-8070-4db4-8961-2a32a1f32024.png">

# Acceptance Criteria

- [ ] All Inputs are required, show warning if empty.
- [ ] A submit button is required
- [ ] Input fields must be labeled  

# Tasks

(for developers team)

- [ ] Test is written for all input fields 
- [ ] Test is written for the submit button  
- [ ] Input fields are created for the topics first name, last name, phone number, e-mail, company name and the website    
- [ ] Input fields for "website" is labeled as a hyperlink 
- [ ] All fields except "website" are strings
- [ ] All information provided by the user are stored in the database

# Complexity
M

**Comment by PReichetanz** [comment]
Hello Raimar,

looks good so far, but I have some questions I am not sure about (and thus I want you to think about them as well:
- How does the warning look like if the input are left empty? You can add a wireframe here as well.
- Are the labels inside of the input fields? What happens if I start writing, do I still see what kind of information I have to put into this field? (Hint: Do you want to implement labels as well as placeholders here?)
- What exactly is the submit button, the one with the "+" on it?
- Why are "Social Media" and "Slack" below the submit button (the one with +), are they input fields as well, but do not really belong to the other inputs?
- "to store the data at the server": Do you already have one (I rather hope not, because it is quite early)? If not, it's fine, implementing localStorage (or later a DB) is a big user story in its own.
- After submitting, where are the data displayed / what happens with them? If you already have implemented a page to display data, add it to the description and link it with an arrow.

**Comment by raimartontsch** [comment]
Moin @PReichetanz, 

many thanks for your input and your ideas! It made me rethink the structure and features at some points. I updated this user story so far and hope it is an upgrade ;)

Notes on your comment: 
- Warning message: wire frame will be added
- labels: updated
- Submit button: I plan to work with symbols over text in order to keep the as simple as possible. To be honest, not sure at this point if it works out but at least I want to give it a try ;) 
- "Social Media" and "Slack" were examples for input fields. At this point I want to focus on the main information so I updated the wire frame. At a later point I will maybe add so more input fields. 
- Data server is planned, not implemented yet ;)         
- I now added a "confirm page" to my concept. Thanks! :) Not sure how to link with a arrow but I will figure it out ;) Tips are welcomed as well ;)

**Comment by mbosselmann** [comment]
Moin Raimar,
I like your user story. 

I only have one **question**: Is the confirm page a feature that has a user story? Then it would be good to link to this user story to show where the data is rendered that is submitted with this form. 
If this confirm page will be implemented later I think it would be better to include in this user story what will happen with the data that is submitted through this form as, if not, the feature at its current state won't make any sense for the user (User perspective: I can submit my data, but nothing is happening?). For example: The data will be dislayed below the form.

For your question regarding links for your confirm page: Maybe [this section of the Next.js docs](https://nextjs.org/docs/api-reference/next/router) will be helpful while working on this code. :)

**Comment by raimartontsch** [comment]
Hello @mbosselmann , 

thanks for your feedback! 
The user story for the confirm page is not finished, yet. It was a good tip by @PReichetanz. But maybe I'll handle it differently leading the user directly to the profile page in order to confirm there. I have not decided yet. 

Also thanks for sharing the section of next.js with me! I am pretty sure it will make my life easier ;)
